### ISSUE TITLE
Duplicated occurrence records

### ISSUE THREAD

**Issue by dagendresen** [bionomia/bionomia#106]
Some occurrence records seem to be duplicated in Bionomia?

Example: https://bionomia.net/agent/4428711

Same gbifID, datasetKey, occurrenceID, etc

<img width="1584" alt="Vidar Bakken Agent 4428711-CSV" src="https://user-images.githubusercontent.com/4330242/111466573-c265f900-8723-11eb-9481-06066bc9e3b2.png">

<img width="1504" alt="Vidar Bakken Agent 4428711" src="https://user-images.githubusercontent.com/4330242/111466950-32747f00-8724-11eb-9941-2643dbccf213.png">

For reference, these are the corresponding occurrences in GBIF

https://www.gbif.org/occurrence/search?basis_of_record=MATERIAL_SAMPLE&basis_of_record=PRESERVED_SPECIMEN&recorded_by=Vidar%20Bakken&advanced=1&occurrence_status=present

<img width="1625" alt="Screenshot 2021-03-17 at 13 17 43" src="https://user-images.githubusercontent.com/4330242/111467128-618af080-8724-11eb-927f-0de3d469f7bc.png">

**Comment by dshorthouse** [comment]
Good spotting! Looks like an artifact of the underlying query rather than true duplicates. In your examples here, all specimens were collected and identified by the same "agent string". I see I used the equivalent of UNION ALL for these instead of UNION, perhaps for performance reasons. I just now deployed a fix to use the former so will see what that might do to performance.
