### ISSUE TITLE
Science anabled download

### ISSUE THREAD

**Issue by JCGiron** [bionomia/bionomia#109]
From SiB Colombia webinar by Carolina Londoño Sánchez:

An option to download the list of publications including specimens by institution and researcher.

**Comment by dshorthouse** [comment]
Would this download additionally include the precise specimens that were included in the download from GBIF, used as the source of data for analyses for the paper?

I am somewhat reluctant to include such a downloadable list for the institution here because there is a subtlety in what exactly these papers represent. They are lists of papers that made use of specimens included in a download that are linked to people that are or were staff. They are NOT about specimens housed within the institutions. In other words, if a taxonomist employed by a museum visits another museum to identify their specimens, this is what is being counted. If an institution desires information like this for their own specimen data, they might be better served to get such a list from GBIF itself. That said, GBIF does not track (or at least does not reveal) specimen-level linkages to downloads made in support of papers. They only track dataset-level linkages.

**Comment by JCGiron** [comment]
I think we can close this one. Given that the question was not much like "can I download the list of papers", but more: "how does Bionomia extract this information.
SiB Colombia received your explanation about it. It is now a matter of time for them to share this with the webinar's attendees.

**Comment by dshorthouse** [comment]
I'm going to leave it open for now. I think there's some merit to offering a download for users. That for institutions is of dubious value. What I need to figure out it what download structure is useful. Someone may wish to have a list of all their specimens (either collected or identified) that were cited in this way via downloads on GBIF vs. a basic list of papers that would not have that specimen-level granularity.
