### ISSUE TITLE
ORCIDs in recordedByID sometimes not linking up collectors with specimens?

### ISSUE THREAD

**Issue by rukayaj** [bionomia/bionomia#168]
An example is https://www.gbif.org/occurrence/1702307774 (Atriplex glabriuscula, catalog number 47990) Kåre Arnstein Lye is the collector, and his ORCID is published in recordedByID. But here https://bionomia.net/help-others/Q15975568?page=1 that specimen is listed as not attributed. 

I think it might be either because:

1) his wikidata QID is on bionomia https://bionomia.net/Q15975568 and it's showing that he's dead (which he is, he died recently). I see you and dag discussed something like this here https://github.com/bionomia/bionomia/issues/96. So perhaps you aren't looking at ORCIDs for matching if you've got someone registered as dead, or something like that?

or 2) Tore Berg (the other collector) has a wikidata QID listed in the recordedByID and that wikidata QID has unfortunately (and incorrectly) been deleted (@dagendresen is trying to overturn this decision on wikidata at the moment). So perhaps this broken QID is breaking it somehow?

**Comment by dshorthouse** [comment]
Thanks @rukayaj. Do you know if the `recordedByID` content was added for https://www.gbif.org/occurrence/1702307774 before September 25, 2021? That's the last download made from GBIF and am presently working through another. It's possible that Tore Berg's deleted item has thrown a wrench in the machines and took Kåre Arnstein Lye link with his because the two would have been handled in the same processing job at Bionomia's end. I'll take a closer look.

**Comment by dagendresen** [comment]
The [latest version of the dataset on the IPT](https://ipt.gbif.no/resource?r=o_vascular) where this record is published is from 2021-09-10 -- so, yes, before September 25, 2021.
