### ISSUE TITLE
As a user I would like names sorted alphabetically in the Agent String search

### ISSUE THREAD

**Issue by mjy** [bionomia/bionomia#174]
When I see a list of names, and I am searching for synonyms of myself, then I have to look at the whole list, when many could be side/by/side enhancing potential issues?

<img width="1783" alt="Screen Shot 2021-11-04 at 11 35 13 AM" src="https://user-images.githubusercontent.com/22600/140380786-9b2da0c5-832d-4971-ab04-3479abb26aa6.png">

**Comment by dshorthouse** [comment]
That's a tricky one. Elasticsearch scores are used for the sort, which operates on weights of various parts of names. See https://github.com/bionomia/bionomia/blob/master/helpers/query_helper.rb#L8. What you see here are agent name strings that come back with roughly equal weight & so it's a blast of everything. Contrast the resultset ordering with a search for "M. Yoder". Something so simple is maddeningly hard because it'll affect paging. Will require some digging.

**Comment by dshorthouse** [comment]
OK, I might have something here to play with that can use both scores and specific fields https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html

**Comment by mjy** [comment]
Could just sort client side?  That is a small number of names?

**Comment by dshorthouse** [comment]
Could. But, would hate to introduce any conditions that need to watch for resultset size. Contrast yours with https://bionomia.net/agents?q=Smith :)~

**Comment by mjy** [comment]
So desperately want to paste an Agent Smith meme... but issue ethics.

**Comment by dshorthouse** [comment]
Done, deployed, and re-indexed! Thanks for the prompt.

**Comment by mjy** [comment]
*Much* better, and far more informative IMO.  One letter difference scream out.  Thanks for the super speed!
