### ISSUE TITLE
As a big-picture thinker I would like to see some simple summary statistics 

### ISSUE THREAD

**Issue by mjy** [bionomia/bionomia#202]
* In 'Scribes" I read:
>  182 people who have attributed natural history specimens to their peers, mentors, and role models 

I woud like to read:
>  182 people who have attributed 999,999,999 natural history specimens to 888888 of their peers, mentors, and role models 

* In 'Datasets" I read:
> 22,491 datasets from GBIF 

I would like to read:
> 22,491 datasets from GBIF, 7,000 touched by Bionomia, 6000 untouched 

I'm not sure if "touched" is the word to use, I'm looking for those given any ORCiD id vs. those not.

* This would help me find datasets with zero (are there such) ORCiD ids

I would like to see:
* Each dataset is heatmapped to show the proportion of records that "Bionomia" identifiers

* In 'Profiles I read on each card:
> 10 specimens claimed

I would like to read:
> 10 specimens claimed from 5 different datasets

* In a new tab 'Summary' I would like to see:
  * Plots of of claims / day
  * Plots of new roles vs. total roles (unique people) added per day
  * Plots of datasets touched vs. total datasets  per day
  * Plots of scribes active vs. roles added per day
  * Perhaps these could be served, to start, as a summarizing JSON endpoint

**Comment by dshorthouse** [comment]
Thanks, @mjy these are great suggestions. Some of these will be a bit tricky to do realtime for performance reasons as well for reasons of i18n. So, it's likely that the best bet is to compute them once a day.

Instead of "datasets", which I've become less and less enamoured with, I may be instead look at institutionCode – there's greater possibility for links to wikidata, though still quite messy.

FWIW, there are now 30M actions taken between occurrence (~specimen) record and collector/determiner, with ~2M of these from sources via identifiedByID or recordedByID.

**Comment by dshorthouse** [comment]
Took a reasonable crack at this in the spirit of the big-picture, though not precisely the same as what you hand in mind. I've not done anything with datasets until I figure out what is most meaningful. One thing I may do is provide a list of datasets that have `recordedByID` or `identifiedByID` populated. Will close for now and revisit later. https://bionomia.net/statistics
