### ISSUE TITLE
Feature: Add Country to Advanced Search and Filter

### ISSUE THREAD

**Issue by debpaul** [bionomia/bionomia#214]
As a Scribe, I know that [David Crockett Graham](https://www.wikidata.org/wiki/Q4151011) did A Lot of collecting in China / Tibet regions. In the [agent strings interface](https://bionomia.net/agent/257616?order=country&sort=asc&datasetKey=&taxon=), I can search for strings (example David C Graham) and then sort by country. The ones from China are likely ALL this particular person.

In Help Attribute, using the Advanced Search and Filter, if Country is added as a Filter, I could then attribute these all more easily.

Well, perhaps I just download the CSV and do the sort and attribute there. So, just an idea David.

**Comment by dshorthouse** [comment]
That agent filter/sort is comparatively easy to implement because there's very little going on in the backend: two tables, one join. In the Help Attribute (or Profile) pages, there's a lot more logic going on (aliases, uses of search in realtime, joins to three+ tables) such that sort is much trickier to implement. I know it's a nuisance to use "Advanced Search" but I can add filtering for country there without much effort so this is a good suggestion. In fact, Country was not even listed in the table as it is with Agents so that should be added as a column too. If I don't add that column, filtering by country would be rather unsatisfactory.
