### ISSUE TITLE
missing link (due to wrong Institution ID?)

### ISSUE THREAD

**Issue by sharifX** [bionomia/bionomia#220]
I am trying to attribute this record (https://www.gbif.org/occurrence/2434489393) to this collector (https://bionomia.net/Q61390). I verified that this is correct attribution. However, the occurrence record does not show up in Bionomia. Is it because "Institution ID" cannot be matched? Is Bionomia looking for a different code? Thanks for looking into this.

**Comment by dshorthouse** [comment]
Hi @sharifX. `institutionID` is not a term included in the Bionomia download from GBIF, whereas `institutionCode` is. There was no particular reason for this other than the presentation of such values in aggregate on eg https://bionomia.net/Q61390/deposited-at seemed like a tricky thing to do for human consumption because sometimes these appear to be URLs and other times not. I see that the `institutionID` term was used for this record with a value, "Naturalis Biodiversity Center" rather than perhaps a more appropriate value, http://biocol.org/urn:lsid:biocol.org:col:34992 or even https://ror.org/0566bfb96. I see the `institutionCode` is RMNH, at least according to https://www.gbif.org/grscicoll/institution/0e919a55-08d3-4bd2-aec1-200858fafd92 but this term is not populated. Would it be possible to repair these at your end? You had in fact attributed this particular record on the 21st of last month, https://bionomia.net/occurrence/2434489393.

**Comment by sharifX** [comment]
Hi @dshorthouse 
thanks for looking into this. I understand the issue now. Yes, we can try to fix it in our end. And we also have several institutionCode for Naturalis in GBIF. We will need to fix that also.
