### ISSUE TITLE
Spurious "recordedBy" assertions

### ISSUE THREAD

**Issue by rdmpage** [bionomia/bionomia#226]
Browsing some data I came across a lot of specimens that were attributed to a profile for no reason that I can see. For example, looking at https://bionomia.net//0000-0003-4013-3804/specimens.jsonld?page=1 (Alexandre Monro ORCID 0000-0003-4013-3804) we see specimens such as

```
   "recorded": [
      {
        "@type": "PreservedSpecimen",
        "@id": "https://bionomia.net/occurrence/2436637894",
        "sameAs": "https://gbif.org/occurrence/2436637894",
        "datasetKey": "4ce8e3f9-2546-4af1-b28d-e2eadf05dfd4",
        "license": "https://creativecommons.org/licenses/by/4.0/legalcode",
        "occurrenceID": "90c0fff6-48f6-4143-8ea4-c9f38a8df5bb",
        "basisOfRecord": "PRESERVED_SPECIMEN",
        "dateIdentified": "2003-01-30",
        "decimalLatitude": "-34.4317",
        "decimalLongitude": "150.4581",
        "country": "Australia",
        "countryCode": "AU",
        "eventDate": "1999-09-27",
        "year": "1999",
        "kingdom": "Plantae",
        "family": "Fabaceae",
        "identifiedBy": "Collins, B.",
        "institutionCode": "MEL",
        "collectionCode": "MEL",
        "catalogNumber": "MEL 2189549A",
        "recordedBy": "Chandler, G.T.",
        "scientificName": "Bossiaea obcordata",
        "typeStatus": null,
        "recordedByID": "https://orcid.org/0000-0003-4013-3804 | http://www.wikidata.org/entity/Q21508256",
        "identifiedByID": null
      },
```

How is a specimen collected by "Chandler, G.T." recorded by Alexandre Monro? Some of these assignments are in GBIF, e.g. https://www.gbif.org/occurrence/2435391031 . 

I don't know how common this is (I guess I could actually to a SPARQL query to try and find out).

**Comment by dshorthouse** [comment]
Welcome to the world reconciling "authoritative" assertions against authoritative sources...and then keeping it all in sync because occurrence data are a moving target. No idea what happened here, but the Bionomia view of that occurrence is https://bionomia.net/occurrence/2435391031 where you can see who made the assertion. Bionomia parses then resolves content in `recordedByID` against ORCID and wikidata, but then does nothing beyond that point. It *could* cross-validate against the parsed agent strings from `recordedBy` (in a bid to check if a publisher flubbed it), but this will be a grey zone because there may be legitimate disambiguation activities at the source whose wikidata Q number or ORCID ID look *nothing* like the content in `recordedBy`. In this case, it looks like the publisher flubbed it.

**Comment by dshorthouse** [comment]
Looks like these particular records have fixed themselves from upstream changes. Will close this ticket, but do need something to wholesale check the veracity of attributions.
