### ISSUE TITLE
As a benefactor of other's volunteer work I want to know who to thank.

### ISSUE THREAD

**Issue by mjy** [bionomia/bionomia#324]
As a collector or identifier who as benefited (example only below) from the kind work of volunteers around the globe I would like to know who to thank.  I.e. I'd like to "roundtrip", and get back to those who came to me.

<img width="1354" alt="Screenshot 2023-12-07 at 2 09 39 PM" src="https://github.com/bionomia/bionomia/assets/22600/1f5a2c55-c112-4661-8836-eb2cf86fb7f3">

**Comment by mjy** [comment]
Aha!  Found it: https://bionomia.net/0000-0002-4098-5823/support (thanks @debpaul).

**Comment by dshorthouse** [comment]
In your own profile, there's a comparable place where you can see who helped and actually send a "thanks", though nowhere near sophisticated as it could be. On the receiving end, the recipient of a "thanks" receives a notice...and a warm tepid? fuzzy feeling 😁

**Comment by dshorthouse** [comment]
Ha! Coincidentally, an earring was found at work today among the dead insects at the Canadian National Collection that looked exactly like that symbol. Perhaps it was tossed by the wizard because the animated corpse failed to answer questions and merely complained about being impaled by a size 2 pin.

**Comment by dshorthouse** [comment]
Closing as it seems to be resolved for now.
