### ISSUE TITLE
Create a csv for a user to download all their attributions made

### ISSUE THREAD

**Issue by dshorthouse** [bionomia/bionomia#352]
See https://github.com/bionomia/bionomia/discussions/346#discussioncomment-9063015 for details.

**Comment by dshorthouse** [comment]
CSV download for attributions made available from the "People Helped" tab in one's profile.

**Comment by abubelinha** [comment]
Thanks and sorry for my delayed answer. 
I had completely missed the resolution of this because I was not automatically subscribed to this issue.
(I expected an answer in the other thread)

That's indeed a much bigger file than I expected since there are many extra helper fields (so I don't need to download anything else from GBIF to get the whole picture).  That saves me a lot of work. 
Thanks a lot for including them! 
Do you plan this to be a stable feature or might you still remove some of those fields?

@abubelinha

**Comment by dshorthouse** [comment]
- `BIONOMIAcreated` is the UTC timestamp for when your attribution was created; these should be static (though as mentioned, not necessarily persistent)

- `dateIdentified` and `identifiedBy` _should_ be headers the download (it is in mine), please let me know if it is not & I will investigate.

- The csv is streamed out with the download (for now) & so should be stable because it's the same as that produced for files that are streamed out to file then uploaded to Zenodo for each user, just with a slightly different query. It'd be better (I think) to use the URI forms of wikidata Q numbers and ORCID IDs because that's what'd be recommended in proper `identifiedByID` or `recordedByID`. Q numbers across wikibases would not point to the same entity & the ORCID IDs without the domain are identical in form (but not resolution) to other ISNIs. I agree that just one column would/could be used here, but preferred not to make a new, undocumented column.

- the file is streamed out in parallel with the looping queries. If there's evidence (through logs) that the ~350 scribes execute repeat and frequent downloads, I'll turn this into a scheduled task with storage on-disk.

**Comment by abubelinha** [comment]
OK, thanks so much for the explanations.
And sorry, I missed `dateIdentified` but it is indeed in my csv.
