### ISSUE TITLE
Support for personal IDs other than ORCID

### ISSUE THREAD

**Issue by Archilegt** [bionomia/bionomia#55]
Please, add support for people who do not have (or refuse to have) an ORCID but do have or are willing to have other identifiers, like VIAF. Thanks.

**Comment by dshorthouse** [comment]
Thanks for the suggestion, but doing so requires the development of a user account system complete with passwords, account recovery via email, and all those other corollary functions we take for granted on a platform that has full-fledged user accounts. This is not something Bionomia will ever have. The requirement to accept any other identifier is OAuth2 for remote authentication whereby users self-identify (with passwords stored elsewhere) and APIs that returns identifying information about the user.

**Comment by Archilegt** [comment]
Thanks for the explanation. Edit: "like VIAF" to "like OpenID".

**Comment by dshorthouse** [comment]
Indeed, "like OpenID" is close. That's an older technology precursor to OAuth2. The take-home here is that the authority provider must have OAuth2 and an API...and then there would be some not insignificant work & custom code to integrate it. For example, if a user of Bionomia chooses to authenticate with whatever that non-ORCID service may be, then they ought not have the option to send archives of their their specimen data to Zenodo because it uses ORCID's OAuth2 service (eg see DOI button on https://bionomia.net/0000-0001-9008-0611)

**Comment by Archilegt** [comment]
Ok. Then I am locked out for the time being. I won't be one more person using an ID with a growing history of forceful adoption. I guess that I will have to get used to being locked out of things, as I am already prevented from publishing in certain journals that force authors to have ORCIDs. Or who knows, maybe an institution will assign me an ORCID without me knowing it, as it has already happened to other people.
I do want to contribute to Bionomia though. If there is anything that I could do without signing in, just let me know.

**Comment by dshorthouse** [comment]
Not sure I'd use the phrase forceful adoption. Aggressive integration, perhaps. I know of no other not-for-profit initiative that has comparable goals and is geared to academics. Nonetheless, here's a longstanding ticket that remains open until I can find something equivalent to what ORCID offers re: authentication, #15 

In the meantime, there is *always* a need for biographical data to be in the open and to be machine-readable. Wikidata is probably the best place for these data because they can then be widely re-used. One way to assist with Bionomia (and all other projects) is to add missing collectors to Wikidata & link them to external sources. Bionomia looks for people items that have a value for the property, [Entomologists of the World](https://www.wikidata.org/wiki/Q5046638) and who also have a date of death.

**Comment by Archilegt** [comment]
David, the ORCID initiative is not-for-profit, but the implementation is not. ORCID has for-profit members paying membership fees and then 1) building for-profit tools on top of ORCID IDs and 2) making ORCID IDs mandatory in journals. Those tools and journals are then sold back to public institutions, priced with profit margins of up to 37%, higher than the profit margins of oil companies. That is why it is so counterproductive, expensive and unfair to turn anything into a standard when the full not-for-profit implementation cycle is far from existing. In an ideal world, the full implementation cycle, with ORCID expenses, tools and journals would be not-for-profit. Then I would have no ethical problem in getting an ORCID.
Forceful adoption happens when the institutions buying a tool get an ORCID-based added service in a pricing bundle that they cannot refuse unless that they refuse the whole package. Forceful adoption happens when all or most of the journals where you can publish in demand you to have an ORCID. For tracking this second, ever growing problem, you can follow this link: https://orcid.org/content/requiring-orcid-publication-workflows-open-letter. 
Thank you for opening the authentication issue. It gives me hope. :)
I will see what to do with Wikidata. As I have no tool to push information in any direction between Wikidata and Myriatrix, I will have to create people's bios in Myriatrix first and then manually input the data into Wikidata again and link it to Myriatrix as external source. And I will have to learn how to edit in Wikidata, but that is something that I am willing to do. :)
Cheers!

**Comment by dshorthouse** [comment]
This is an interesting position and I'll think more about it. Thanks for sharing. I have always equated ORCID with Crossref in their financial arrangements with publishers & so have not stopped to consider that both have the potential to or are generally doing harm to science.

**Comment by abubelinha** [comment]
Related to some of the above comments:
https://info.orcid.org/documentation/integration-and-api-faq/#easy-faq-2364
> ORCID offers several APIs that allow your systems to connect to the ORCID registry, including reading from and writing to ORCID records. **Some** API functions are **freely** available to anyone (Public API); **others are only available to ORCID member** organizations (Member and Premium Member API). 
> (...)
>- How do I add items to an ORCID record?
Items (works, employment, funding, peer review etc) can be added to an ORCID record using the **ORCID member** API.

In other words: I have to pay them in order to fill in their database? 
Either paying with my life time (spend hours filling in their web interface) or with my money (pay member api to speed up process).  
No thanks. I agree with @Archilegt  
Does not sound like "_not for profit_" to me.

**Comment by dshorthouse** [comment]
> In other words: I have to pay them in order to fill in their database?
> Either paying with my life time (spend hours filling in their web interface) or with my money (pay member api to speed up process).

Some details like your work affiliations, "also known as name(s)" are indeed manual, quick, and I assume in most cases, infrequently changed. Entry of publications, datasets, and other such items can be automated if (a) you use your ORCID & it's included in the publisher's metadata to CrossRef or DataCite, and (b) you configured CrossRef and DataCite (among others) to be one of the resources that ORCID watches on your behalf. See the "Trusted Parties" menu item in your ORCID account. If you are an organization/consortium & wish to bulk import items on behalf of employees or consortia members, that's a paying service through use of ORCID's write API. The read API is free & I use it in Bionomia.

**Comment by abubelinha** [comment]
I prefer to control the stuff shown in my ORCID record, rather than letting ORCID decide for me.
If it is "open" and "community-built", it does not make sense that community people have to pay the api for building their own records.

> use ORCID's OAuth2 API to freely write your own items into your own account, but I assume that might be possible.

I don't think so. The above [faq entry](https://info.orcid.org/documentation/integration-and-api-faq/#easy-faq-2364) says "_items can be added **using the [ORCID member API](https://info.orcid.org/register-a-client-application-production-member-api/)**_".

And the [public API](https://info.orcid.org/documentation/features/public-api/) seems clearly limited to reading/searching actions, but not writing (not even to your own account record):
> The public API can be used for the following functions:
> - [**Sign in**to your system with ORCID](https://info.orcid.org/documentation/features/public-api/orcid-as-a-sign-in-option-to-your-system/)
> - [**Get** a user’s verified ORCID iD](https://info.orcid.org/documentation/features/public-api/using-the-orcid-api-to-collect-authenticated-ids/)
> - [**Retrieve** public data from a user’s ORCID record](https://info.orcid.org/documentation/features/public-api/reading-orcid-records/)
> - [**Search** public ORCID registry data](https://info.orcid.org/documentation/features/public-api/searching-the-registry/)

**Comment by dshorthouse** [comment]
> I prefer to control the stuff shown in my ORCID record, rather than letting ORCID decide for me.

To each their own. For what it's worth, you can show/hide/delete every single item in ORCID, even those that may have arrived via automated means such as CrossRef, DataCite or other.
