### ISSUE TITLE
Add advanced search and filter to candidate records in user profile

### ISSUE THREAD

**Issue by dshorthouse** [bionomia/bionomia#56]
Advanced search and filter works reasonably well in Help Others, but it would be nice if this was also in a user's own profile.

**Comment by JCGiron** [comment]
Along these lines, it would be nice if the taxonomic filter could be for higher taxonomic levels. For example, I know certain agent did not collect or identify plants or vertebrates, so it would be nice to be able to exclude all those records for them in block. As it turns out there are several Duque, Florez and Jimenez botanists and entomologists... it seems like botanists have way more data than entomologists. I was trying to assign records to the entomologists, but there are just way to many plant and vertebrate records that it would be nice to discard up front.

**Comment by dshorthouse** [comment]
This is a good suggestion but will require more data pulled from GBIF. I'm shying away from managing any hierarchy...for reasons. I'll create a new ticket for this one.
