### ISSUE TITLE
Converting ORCID to wikidata in admin for deceased results in duplicate search item

### ISSUE THREAD

**Issue by dshorthouse** [bionomia/bionomia#96]
As in the subject.

**Comment by dagendresen** [comment]
Would it not rather make more sense to keep the Bionomia profile based on the ORCID ID -- when a deceased person has both an ORCID ID and a QID?

Example
https://bionomia.net/0000-0003-0398-890X --->
https://bionomia.net/Q15975568

**Comment by dshorthouse** [comment]
@dagendresen If that once ORCID-base profile was not public it would remain hidden forever – only the ORCID owner can make their profile public. The switch and redirect to QID means anyone may make it publicly available.

**Comment by dagendresen** [comment]
Then maybe display the ORCID also on the "new" QID-based Bionomia profile page? (display the ORCID on all QID-based profile pages when an ORCID is available from the Wikidata entry?)

**Comment by dshorthouse** [comment]
I might be able to do that, though will require some redesign – presently, much of the presentation assumes an either/or. May I ask what might be the use case?

**Comment by dagendresen** [comment]
No specific use case - only the principle of an ORCID a "higher level" PID than the QID... (more unique and more persistent)

**Comment by dshorthouse** [comment]
Fair enough. I'll investigate what this might require though cannot yet say for certain how tricky this might be. Part of me is a bit concerned not for the work on a technical fix, but for how to best communicate what's going on. "ORCID for the living, Wikidata for the deceased" has become somewhat of an entrenched mantra.

**Comment by dagendresen** [comment]
Apropos -- a link to the Wikidata entry would be useful also on the ORCID-based Bionomia profile pages ---> Use case: to more easily/quickly describe current (alive) naturalist (many ORCID profiles have few details -- and lack many of the Wikidata-attributes which are useful when assigning Bionomia annotations). 

In other words, it might useful to display both the ORCID ID and Wikidata QID when both/either are/is available :-)

PS: At PIDapalooza2021 the topic of an ORCID-like ID for deceased people was a popular topic...

PPS: Maybe (in a much larger scope) the museums might consider a mechanism to manage [ISNI IDs](https://support.orcid.org/hc/en-us/articles/360006973973-What-is-the-relationship-between-ISNI-and-ORCID-#:~:text=ORCID%20was%20established%20to%20solve,research%20output%20to%20individual%20researchers.&text=ISNI%20has%20reserved%20a%20block,%2D0003%2D5000%2D0001.) for (all?) naturalists (instead of depending on Wikidata QIDs???).
